=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/XMLs/partie3/java-code.dtd
<!ELEMENT java-code (model|primitive)*>
        <!ELEMENT model (#PCDATA)>
        <!ATTLIST model
                name CDATA #REQUIRED
                package CDATA #REQUIRED>

        <!ELEMENT primitive (#PCDATA)>
        <!ATTLIST primitive
                name CDATA #REQUIRED
                package CDATA #IMPLIED
                type CDATA #REQUIRED>

=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/src/main/resources/XMLs/partie3/figure16.xml
<?fr.ubo.m2tiil.louarn.xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE java-code SYSTEM "java-code.dtd">
<java-code>
    <model name="Meuble" package="m2tiil.meuble"/>
    <model name="Bataille" package="m2tiil.batailleNavale"/>
    <primitive name="String" type="String"/>
    <primitive name="Integer" type="Integer"/>
    <primitive name="List" type="ArrayList" package="Java.util.ArrayList"/>
    <primitive name="Array" type="Array" package="m2tiil.Array"/>
    <primitive name="Set" type="HashSet" package="Java.util.HashSet"/>
    <primitive name="Bag" type="Bag" package="m2tiil.Bag"/>
</java-code>
