=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/XMLs/partie2_3/minispec.dtd
<!ELEMENT modele (entity)*>
        <!ATTLIST modele >

        <!-- entity -->
        <!ELEMENT entity (attribute
                |array
                |collection
                |typeElement)*>
        <!ATTLIST entity
                name CDATA #REQUIRED
                subtype CDATA #IMPLIED
                >
        <!-- attribute -->
        <!ELEMENT attribute (attribute
                |array
                |collection
                |typeElement)*>
        <!ATTLIST attribute
                name CDATA #REQUIRED
                >
        <!-- typeElement -->
        <!ELEMENT typeElement EMPTY>
        <!ATTLIST typeElement
                type CDATA #REQUIRED
                >
        <!-- array -->
        <!ELEMENT array (attribute
                |array
                |collection
                |typeElement)*>
        <!ATTLIST array
                name CDATA #REQUIRED
                size CDATA #REQUIRED
                >
        <!-- collection -->
        <!ELEMENT collection (attribute
                |array
                |collection
                |typeElement)*>
        <!ATTLIST collection
                name CDATA #REQUIRED
                min CDATA #IMPLIED
                max CDATA #IMPLIED
                >

=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/XMLs/partie2_3/figure10.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE modele SYSTEM "minispec.dtd">

<modele>

	<entity name="Satelite">

		<attribute name="nom" type="String" />

		<attribute name="id" type="Integer" />

		<attribute name="parent" type="Flotte" />

	</entity>

	<entity name="Flotte">

		<collection name="satelites" type="List"
			typeElements="Satelite" />
		<array name="satelites" size="10" type="Satelite" typeElements="Satelite"/>

	</entity>

</modele>
