=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/src/main/resources/XMLs/minispecXml/minispec.dtd
<!-- modeleMinispec -->
<!ELEMENT modeleMinispec (entity)*>
<!ATTLIST modeleMinispec
        name CDATA #REQUIRED
        >

<!-- entity -->
<!ELEMENT entity (attributeMinispec)*>
<!ATTLIST entity
        name CDATA #REQUIRED
        supertype CDATA #IMPLIED
        >

<!-- attributeMinispec -->
<!ELEMENT attributeMinispec (
        array
        |collection
        |typeElement)>
<!ATTLIST attributeMinispec
        name CDATA #REQUIRED
        >

<!-- typeElement -->
<!ELEMENT typeElement EMPTY>
<!ATTLIST typeElement
        type CDATA #REQUIRED
        >

<!-- array -->
<!ELEMENT array (
        array
        |collection
        |typeElement)>
<!ATTLIST array
        size CDATA #REQUIRED
        >

<!-- collection -->
<!ELEMENT collection (
        array
        |collection
        |typeElement)>
<!ATTLIST collection
        typeCollection CDATA #REQUIRED
        min CDATA #IMPLIED
        max CDATA #IMPLIED
        >

=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/src/test/resources/XMLs/minispecXml/minispecEnMinispec.xml
<?fr.ubo.m2tiil.louarn.xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE modeleMinispec SYSTEM "minispec.dtd">

<modeleMinispec name="fr.ubo.m2tiil.louarn.minispecEnMinispec.modele.minispec">

    <entity name="Modele">
        <attributeMinispec name="name">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="entites">
            <collection typeCollection="List">
                <typeElement type="Entite"/>
            </collection>
        </attributeMinispec>
    </entity>

    <entity name="Entite">
        <attributeMinispec name="name">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="subype">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="attributs">
            <collection typeCollection="List">
                <typeElement type="Attribute"/>
            </collection>
        </attributeMinispec>
    </entity>

    <entity name="Attribute">
        <attributeMinispec name="name">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="type">
            <typeElement type="Type"/>
        </attributeMinispec>
    </entity>

    <entity name="Type">
    </entity>

    <entity name="Array" supertype="Type">
        <attributeMinispec name="type">
            <typeElement type="Type"/>
        </attributeMinispec>

        <attributeMinispec name="size">
            <typeElement type="Integer"/>
        </attributeMinispec>
    </entity>

    <entity name="Collection" supertype="Type">
        <attributeMinispec name="typeCollection">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="type">
            <typeElement type="Type"/>
        </attributeMinispec>
    </entity>

    <entity name="TypeElement" supertype="Type">
        <attributeMinispec name="type">
            <typeElement type="String"/>
        </attributeMinispec>
    </entity>

    <entity name="Repesitory" supertype="Type">
        <attributeMinispec name="modele">
            <typeElement type="Modele"/>
        </attributeMinispec>
    </entity>

</modeleMinispec>

=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/src/main/resources/XMLs/minispecXml/minispecEnMinispec.xml
<?fr.ubo.m2tiil.louarn.xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE modeleMinispec SYSTEM "minispec.dtd">

<modeleMinispec name="minispecModele">

    <entity name="Entity">
        <attributeMinispec name="name">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="subype">
            <typeElement type="Integer"/>
        </attributeMinispec>

        <attributeMinispec name="attributs">
            <collection typeCollection="List">
                <typeElement type="Attribute"/>
            </collection>
        </attributeMinispec>
    </entity>

    <entity name="Attribute">
        <attributeMinispec name="name">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="type">
            <typeElement type="Type"/>
        </attributeMinispec>
    </entity>

    <entity name="Type">
    </entity>

    <entity name="Array" subtype="Type">
        <attributeMinispec name="type">
            <typeElement type="Type"/>
        </attributeMinispec>

        <attributeMinispec name="size">
            <typeElement type="Integer"/>
        </attributeMinispec>
    </entity>

    <entity name="Collection" subtype="Type">
        <attributeMinispec name="typeCollection">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="type">
            <typeElement type="Type"/>
        </attributeMinispec>
    </entity>

    <entity name="TypeElement" subtype="Type">
        <attributeMinispec name="type">
            <typeElement type="String"/>
        </attributeMinispec>
    </entity>

</modeleMinispec>

=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/src/main/resources/XMLs/minispecXml/figure10.xml
<?fr.ubo.m2tiil.louarn.xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE modeleMinispec SYSTEM "minispec.dtd">

<modeleMinispec name="fr.ubo.m2tiil.louarn.minispecEnMinispec.modele.autre">

    <entity name="Satelite">

        <attributeMinispec name="nom">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="parent">
            <typeElement type="Flotte"/>
        </attributeMinispec>

    </entity>

    <entity name="Flotte">
        <attributeMinispec name="satelites">
            <collection typeCollection="List" max="10">
                <typeElement type="Satelite"/>
            </collection>
        </attributeMinispec>
    </entity>

</modeleMinispec>

=== Robin-Ln/M2_Generation_De_Code_UE_Interoperablilite/src/test/resources/XMLs/minispecXml/balise-satellite.xml
<?fr.ubo.m2tiil.louarn.xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE modeleMinispec SYSTEM "minispec.dtd">

<modeleMinispec name="modele">

    <entity name="Satellite">

        <attributeMinispec name="nom">
            <typeElement type="String"/>
        </attributeMinispec>

        <attributeMinispec name="parent">
            <typeElement type="Flotte"/>
        </attributeMinispec>

    </entity>

    <entity name="Flotte">
        <attributeMinispec name="satellites">
            <collection typeCollection="List">
                <typeElement type="Satellite"/>
            </collection>
        </attributeMinispec>
    </entity>

</modeleMinispec>
